### ISSUE TITLE
[QUESTION] Django Debug Toolbar at production

### ISSUE THREAD

**Issue by DmytroLitvinov** [guettli/django-tips#2]
Hi @guettli ,
Thank you for your list of tips.
I am just curious about "that paragraph":https://github.com/guettli/django-tips#django-debug-toolbar-1.
How do you use Django Debug Toolbar at production? I see it is not recommended to use it at production so maybe you have a very specific case and I would be glad to hear it from you.

**Comment by guettli** [comment]
I updated the README. See https://github.com/guettli/django-tips/blob/main/README.md#django-debug-toolbar

Please re-open if something is not clear for you.  Thank you for asking.
